config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, except: [:index, :new]
  resources :sessions, only: [:create]
  resources :games, only: [:create, :destroy]

  get '/game' => 'games#game'
  get '/games/list' => 'games#list'
  get '/start' => 'users#start'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/list' => 'users#list'
  delete '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :additions, dependent: :destroy
  has_many :games, through: :additions

  # It validates the email field for presence and uniqueness.
  validates_uniqueness_of :email
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # It validates the user has a secure password.
  has_secure_password

  # Defines the method used to create a new remember token for the user.
  def User.new_remember_token
    # Creates a 64bit random remember_token.
    SecureRandom.urlsafe_base64
  end

  # Defines the method used for hashing a plaintext remember token
  def User.hash(token)
    # Creates a hash and converts it to a string.
    Digest::SHA1.hexdigest(token.to_s)
  end

  # def add(game)
    #Addition.create(user_id: self.id, song_id: song.id)
    #games << game
  # end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Makes sure firelds are of the proper formatting to avoid conflicts.
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:index, :new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:index, :list, :start, :new, :create]


  def index
    unless !signed_in?
      redirect_to start_path
    end
  end

  def new
    @user = User.new
  end

  def create
    # Sets up a new user using the params passed from the form.
    @user = User.new(user_params)
    # If the user is able to be saved and there are no validation errors, call the sign in method (sessions helper) on the new user and redirect them to the homepage.
    if @user.save
      sign_in @user
      redirect_to root_path
      # Otherwise send them back to the new user form.
    else
      render :new
    end
  end

  def start
    @question_1_answers = [["I Want it All", 'all'], ["I Need to be Where the Action is", 'action'], ["I'm Going on an Adventure", 'adventure'], ["Quarters!", 'arcade'],
      ["My Kids are Watching", 'children%27s'], ["Fun for the Whole Family", 'family'], ["Kickpuncher!", 'fighting'], ["I Believe I Can Fly!", 'flight'], ["Suprise Me", 'other+games/compilations'], ["I'll Take the Case", 'puzzle'],
      ["Vrooooooom", 'racing'], ["Lightning Bolt!!!", 'role+playing'], ["Pew Pew Pew", 'shooter'], ["Like Real life, Only Not", 'simulation'], ["The Roar of the Crowd", 'sport+games'], ["A Brilliant Mind", 'strategy']]
    @question_2_answers = [['Show me EVERYTHING!', 'all'], ['Nintento DS', 'ds'], ["Nintendo GameCube", 'gc'], ["PC", 'pc'], ["PS2", 'ps2'], ["PS3", 'ps3'], ["PSP", 'psp'], ["Nintendo Wii", 'wii'], ["XBox", 'xbox'],
      ["XBox 360", 'xbox360'], ["Sega DreamCast", 'dc'], ["Gameboy", 'gameboy'], ["Gameboy Advanced", 'gba'], ["Sega Genesis", 'genesis'], ["Nintendo 64", 'n64'], ["NES", 'nes'], ["PS1", 'ps1'], ["Sega Saturn", 'saturn'],
      ["Super Nintendo", 'snes']]
    @question_3_answers = [["New is Better", 'newest'],["Classics First", 'oldest'],["A-Z", 'a-z'],["Z-A", 'z-a']]
  end


  def list
    list = HTTParty.get("http://api.gamesradar.com/games?genre=#{params[:genre]}&platform=#{params[:platform]}&sort=#{params[:sort]}&api_key=#{ENV['game_radar_api_key']}&page_size=50")
    @games_list = list["games"]["game"]

    if @games_list.blank?
      flash[:error] = "Sorry, our robots couldn't find a darn thing, \nrest assured they are being punished."
      redirect_to start_path
    end
  end


  private

    # Finds the user based on their ID in params
    def find_user
      @user = User.find(params[:id])
    end

    # Sets what are valid user params to be used in the new & edit methods.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Defines a method used as a before action that requires a user to be the current user to perform certain actions.
    def require_current_user
      if !current_user?(@user)
        redirect_to root_path
      end
    end

end

app/views/users/_user_form.html.haml
<!-- If the user was redirected to this page due to validation errors, display those errors here: -->
- if @user.errors.any?
  %strong Errors:
  %ul
    - @user.errors.full_messages.each do |msg|
      %li
        = msg
<!-- If the user accessed this page directly, or without an errors, display the form to get data -->
= simple_form_for @user do |f|
  = f.input :email, label: "Please enter your email:   ", required: true
  = f.input :password, label: "Please enter your password:   ", required: true
  = f.input :password_confirmation, label: "Confirm password:   ", required: true
  = f.button :submit, "Go", id: "submit", class: "go"

app/views/users/index.html.haml
%h1 Welcome New Player!
= link_to "Sign In", signin_path
|
= link_to "Sign Up", signup_path

app/views/users/list.html.haml
%h1 Check'm Out
- if @games_list.class == Array
	%ul
		- @games_list.each do |game|
			%li 
				= link_to game["name"]["us"], '/game' + "?title=" + URI.encode(game["name"]["us"]), id: 'game_link'
- else
	%ul
		%li 
			= link_to @games_list["name"]["us"], '/game' + "?title=" + URI.encode(@games_list["name"]["us"]), id: 'game_link'

app/views/users/new.html.haml
%h1 Sign Up
= render "user_form"

app/views/users/start.html.haml
%h1 Start
- flash.each do |name, msg|
	= content_tag :p, msg, class: name

= form_tag("/list", method: 'get') do
	= label_tag 'genre', "What Piques Your Interest?", class: 'label'
	= select_tag 'genre', options_for_select(@question_1_answers, selected: @question_1_answers[1]), class: 'answer'
	= label_tag 'platform', "Choose your System:", class: 'label'
	= select_tag 'platform', options_for_select(@question_2_answers), class: 'answer'
	= label_tag 'sort', "Choose your order:", class: 'label'
	= select_tag 'sort', options_for_select(@question_3_answers, selected: @question_3_answers[1]), class: 'answer'
	= submit_tag "Go", class: 'go'