config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, except: [:index, :new]
  resources :sessions, only: [:create]
  resources :games, only: [:create, :destroy]

  get '/game' => 'games#game'
  get '/games/list' => 'games#list'
  get '/start' => 'users#start'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/list' => 'users#list'
  delete '/signout' => 'sessions#destroy'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :additions
  has_many :users, through: :additions

  validates :title,
    presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def game
    @youtube = "https://www.youtube.com/results?search_query="
    get_game_data(params[:title])
    @is_saved = current_user.games.find_by(title: @title)
  end

  def create
    title = params[:game][:title]
    if game = Game.find_or_create_by(title: title)
      Addition.create(user_id: current_user.id, game_id: game.id)
      redirect_to games_list_path
    else
      redirect_to '/game?title=' + "#{title}"
    end
  end

  def list
    @user_games = current_user.games
  end

  def destroy
    Game.destroy(params[:id])
    redirect_to games_list_path
  end


#-----------------------------------------------------------------------------------------------
  private
#-----------------------------------------------------------------------------------------------

    def get_game_data(title)
      title = title.gsub(" ", "+")
      @game = HTTParty.get("http://www.giantbomb.com/api/search/?api_key=#{ENV['giant_bomb_api_key']}&format=json&query=#{title}&resources=game&limit=1")
      @deck = @game["results"][0]["deck"]
      @image = @game["results"][0]["image"]["super_url"]
      @title = title
    end

end



### game = Game.find_or_create_by_title()
### current_user.games << game

app/views/games/game.html.haml
%h1 
	= @title.gsub("+", " ")
=link_to(@youtube+@title) do
	= image_tag @image

%p
	= @deck

- if @is_saved.nil?
	= form_tag games_path do
		= hidden_field :game, :title, :value => @title
		= submit_tag "Add", class: 'go'
- else
	= form_tag game_path(@is_saved.id), method: 'delete' do
		= hidden_field :game, :id, :value => @is_saved.id
		= submit_tag "REMOVE", class: 'button'

app/views/games/list.html.haml
%h1 Your Games:
- if @user_games.empty?
	%p You have not yet saved any games to your list.
	Head over to 
	= link_to "here", start_path
	to find some games
- else
	%ul
		- @user_games.each do |game|
			%li
				= link_to game.title.gsub("+", " "), '/game' + '?title=' + game.title, id: 'game_link'